### ISSUE TITLE
Fix up specification of BBCH growth stage codes

### ISSUE THREAD

**Issue by jnothman** [Sydney-Informatics-Hub/Weed-ID-Interchange#115]
1. Currently called "bbch_code" should be "bbch_growth_stage"
2. Currently specified with gs prefix. This should be made more explicit in the description or with examples, or the gs prefix should be removed.
3. How do we want to allow a range or several BBCH growth stages to be specified? The growth stage is intended to be applied to a single plant, not a plantation.

**Comment by hlydecker** [comment]
From our last discussion of this with Michael, I was under the impression that we want to stick with broader approximate growth stages for the agcontext.

I mean I can see how it might be super useful to have image level growth stage information, but that level of annotation doesn't seem to be a target for now (or any time soon)

**Comment by jnothman** [comment]
Yes, I agree that we should not be annotating per image. So the question being regarded in this issue is how to specify "broader approximate growth stages".

Also, might be good for the name to clarify that this is the _crop_ growth stage, not weed.

**Comment by jnothman** [comment]
Current implementation for growth stage entry uses a range slider.

An alternative design is the following. The challenge is getting a widget that provides for multi-valued entry but with a range constraint; also hard is translating input range between the different description granularities:

![image](https://user-images.githubusercontent.com/78827/106405379-1c6b7180-648a-11eb-87b0-a4abe5a13121.png)

A further alternative might be like the Wikipedia commit range selector: with a radio box for min and max growth stage.

When searching, we should be able to filter on min and max growth stages.
