### ISSUE TITLE
Agcontext editor form

### ISSUE THREAD

**Issue by hlydecker** [Sydney-Informatics-Hub/Weed-ID-Interchange#146]
Research options for react form entry options and develop a tool to allow users to create and export an AgContext yaml based on what they have entered into the form.

**Comment by jnothman** [comment]
This is a react UI which will eventually support:
1. ingesting an agcontext
2. editing the agcontext in a friendly form-based ui
3. exporting the form contents as an agcontext

Initial goal is to design step 2

**Comment by hlydecker** [comment]
So far I have something which functions as a stand-alone agcontext entering form. This is autogenerated using react-jsonschema-form. However it is not pretty; some work with the uiSchema and theme would help with making it more user friendly.

Ideally we would make it so that the form updates if changes are made to the agcontext schema. I've tried setting the form app to source the schema from a file, but that has some weird issues with fields being invalid.

Also agcontext export is currently non functional but I have explored a few options. It looks to be a bit tricky, but hopefully I am missing a simple solution to this (seems like it should be a pretty common need?)

**Comment by jnothman** [comment]
> Also agcontext export is currently non functional but I have explored a few options.

In the demo there's something called `formData`. Is that not the same??

**Comment by jnothman** [comment]
> Ideally we would make it so that the form updates if changes are made to the agcontext schema. I've tried setting the form app to source the schema from a file, but that has some weird issues with fields being invalid.

This does not need to be automatic; it can be done through regeneration and git merging.

**Comment by jnothman** [comment]
`react-jsonschema-form` _does_ look like the way to go, at least initially. You can see from its playground samples that it's able to load in JSON that matches the schema as `formData` (e.g. https://github.com/rjsf-team/react-jsonschema-form/blob/66623b9abad487c00a750014f50ff4d25248759d/packages/playground/src/samples/nested.js#L47-L64), and that it's able to save that back out again.

You can see how to do this in the quickstart guide, under [Controlled Component](https://react-jsonschema-form.readthedocs.io/en/latest/quickstart/#controlled-component). Half the magic is in [`React.usestate`](https://reactjs.org/docs/hooks-reference.html#usestate), which takes the `initialState` as an argument.

**Comment by hlydecker** [comment]
Yeah I got a bit confused with the `usestate` part of exporting `formData` on my first pass.

**Comment by jnothman** [comment]
![image](https://user-images.githubusercontent.com/78827/99339467-550f9c00-28da-11eb-95fc-b0d7e81430cc.png)

**Comment by hlydecker** [comment]
Well if you ask like that :), #151

**Comment by jnothman** [comment]
Editor form now in master.
