### ISSUE TITLE
Automatically find eppo/bayer codes

### ISSUE THREAD

**Issue by hlydecker** [Sydney-Informatics-Hub/Weed-ID-Interchange#16]
Currently we are hard coding most aspects of category objects, however in the future it may be useful to try to automatically fill in information. For example, if we have the scientific name of a plant species, we can then easily query the EPPO API: https://data.eppo.int/documentation/rest#collapse1

**Comment by jnothman** [comment]
Agreed. At the moment we should be focusing on what is sufficient valid information for contributors to submit, i.e. sufficient to query eppo.int, and sufficient for downstream applications.

**Comment by hlydecker** [comment]
I think scientific name might be required, as we had expected. With DeepWeeds, about 1/4 of the weed common names in the annotations did not match with one of the common names that are recognised by EPPO. I suppose if we compiled an up to date set of potential common names we could have those linked to scientific names and other species information.

**Comment by jnothman** [comment]
Not happening any time soon
