### ISSUE TITLE
Need acknowledgement of SIH and GRDC on web site

### ISSUE THREAD

**Issue by jnothman** [Sydney-Informatics-Hub/Weed-ID-Interchange#175]
We need this at the bottom of every page, or at least on the About tab.

The About tab also should give a reference for citing the database... we might need to ask the client about preferences here.

**Comment by jnothman** [comment]
This is currently waiting on @geezacoleman providing About section content.

**Comment by geezacoleman** [comment]
@jnothman did you want an SIH logo on the About page? Text should be good to go today.

**Comment by jnothman** [comment]
and SIH Logo looks a lot like a sydney uni logo, but yes, we should have there.
