### ISSUE TITLE
Confirm that validation errors (e.g. bad category name) are shown to user

### ISSUE THREAD

**Issue by jnothman** [Sydney-Informatics-Hub/Weed-ID-Interchange#185]

**Comment by jnothman** [comment]
Ideally, COCO validation issues should show before image upload, then only agcontext, metadata and image-dependent issues show later.

**Comment by jnothman** [comment]
We should show the message from the exception, while logging the traceback. The message will not be user friendly, but will be better than what we currently have. Might be multiple lines of text.

**Comment by ElevnLi** [comment]
[This is pretty weird](https://github.com/Sydney-Informatics-Hub/Weed-ID-Interchange/blob/a58f4226f7a3bc480ffca776e1d90ea6893502f9/search/src/Components/upload/uploader_single.js#L38-L40)
When I do `console.log(xhr)`, it gives me the right XMLhttpresponse object with the error message in both xhr.response and xhr.responseText, but when I do `console.log(xhr.response)`, it shows me nothing and the length is 0. if I assign xhr to a global variable like `window.res`, then I can access `res.response` from the console.

**Comment by jnothman** [comment]
Sounds like a concurrency issue. Is xhr.response being filled asynchronously.

**Comment by jnothman** [comment]
Not sure why you'd receive `error_upload` before the response is available, though. Maybe the `error` handler is triggered the moment the HTTP status header is parsed, but the response is only read later. Maybe you need to handle the [loadend event](https://developer.mozilla.org/en-US/docs/Web/API/XMLHttpRequest/loadend_event)??

**Comment by jnothman** [comment]
The code in react-dropzone-uploader is quite imprecise, but indeed it looks like handleChangeStatus will first be called with `'error_upload'` when the XHR's [readyState](https://developer.mozilla.org/en-US/docs/Web/API/XMLHttpRequest/readyState) is `HEADERS_RECEIVED`.

**Comment by ElevnLi** [comment]
When it is a failed upload, the sequence of onChangeStatus status would be getting_upload_params -> uploading -> error_upload, and none of the xhr holds the right response. The response only shows correct info after the whole process, and this event somehow cannot be captured.

**Comment by jnothman** [comment]
When you get the error_upload status, bind to the load event (or loadend) on the xhr, and use that binding to set the error in the UI.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________
