### ISSUE TITLE
validate multiple json files as valid Weed COCO

### ISSUE THREAD

**Issue by hlydecker** [Sydney-Informatics-Hub/Weed-ID-Interchange#19]
Currently the validation workflow only really applies to specific files. This probably is fine if we just want to use it to validate a schema. But in the future, would we want to validate any number of JSON files, and perhaps recursively? Using glob, as you had suggested, to get all relevant files for validation might be a good idea in that case. There is a glob in the github actions toolkit, but I don't know if we will need to make our own version of the JSON validation action to make use of this.

**Comment by jnothman** [comment]
The only problem is that the existing action doesn't support globs (issue opened: https://github.com/OrRosenblatt/validate-json-action/issues/19). But there may also be a way to dynamically generate `INPUT_PATHS`.

**Comment by jnothman** [comment]
Done. Currently with hardcoded paths.
