### ISSUE TITLE
Ensure deepweed and cwfid ingesters produce JSON matching schema

### ISSUE THREAD

**Issue by jnothman** [Sydney-Informatics-Hub/Weed-ID-Interchange#24]
I think at the same time we should make their ingestion code .py rather than .ipynb.

**Comment by jnothman** [comment]
Part of this would be:
* having a sample of data in the repo (even if it's fake)
* converting it in a GH Workflow
* testing against the schema in the GH Workflow

**Comment by hlydecker** [comment]
Funny enough I am hung up on something that is probably extremely simple to solve: for deepweeds I want to generate image_id from row/index numbers in the annotations csv file (to match the behaviour in the cwfid conversion).

**Comment by jnothman** [comment]
Use `enumerate`?

**Comment by jnothman** [comment]
Or iRow like [here](https://github.com/Sydney-Informatics-Hub/Weed-ID-Interchange/pull/40/files#diff-60f5fb62a9fa26271585d7daefa36f4bR140)?

**Comment by hlydecker** [comment]
> Or iRow like [here](https://github.com/Sydney-Informatics-Hub/Weed-ID-Interchange/pull/40/files#diff-60f5fb62a9fa26271585d7daefa36f4bR140)?

I had tried something with iRow that was more complex; I hadn't really understood what exactly iRow did :) that fixes it

**Comment by hlydecker** [comment]
The two converters produce jsons that should be mostly identically formatted. We are missing collection memberships for deepweeds, but I think we still need to decide how exactly to deal with collection memberships. I'll leave this issue open in case you run into any issues or find errors.

**Comment by jnothman** [comment]
> The two converters produce jsons that should be mostly identically formatted.

Ideally, we would check that by using a workflow to verify that they match a schema.

As long as an image/annotation can belong to multiple collections, I think the current `collection_memberships` design is about as good as it gets. The alternatives I see are:
* add to image or annotation: {"member_of": {"collection_id": 0, "subset": "train"}}
* add `collection_ids` to image or annotation, and have some other way to represent train/validation/test splits:
  * a listing of membership in the collection object
  * a collection ID is added for both the full collection and the subset
  * some field on the image that is fixed across all collections, saying whether the sample is held out for testing (no more detail)

A problem with both of these is that currently the only cross-referencing we have is with a singular `<type>_id`, directly on the object, not `_ids`. But maybe that's not a concern?

For what it's worth, I like the idea of labelling each sample as held-out or not, and then hiding held-out samples from the UI, and requiring that if a sample is part of a held-out set, it is always part of a held-out set. However, this constrains contributors' abilities to create new datasets.

**Comment by jnothman** [comment]
As well as ideally having them match a schema, we should use `jupyter nbconvert` to change the notebooks to .py, and should refactor the code so that they build on shared components.

**Comment by hlydecker** [comment]
The two converters should 

> As well as ideally having them match a schema, we should use `jupyter nbconvert` to change the notebooks to .py, and should refactor the code so that they build on shared components.

Oops forgot to remove the notebooks; .py versions are already in.

**Comment by jnothman** [comment]
I think this was effectively fixed in #43
