### ISSUE TITLE
Export to ElasticSearch should add a field describing the tasks that can be performed with the annotation

### ISSUE THREAD

**Issue by jnothman** [Sydney-Informatics-Hub/Weed-ID-Interchange#25]
So we should be producing in each image one or more "annotation_types" labels from:
* "classification"
* "bounding box"
* "segmentation"
* "instance segmentation"

We should be able to infer the from the annotations associated with each image....

**Comment by hlydecker** [comment]
e.g.

if annotation contains "bbox":
"annotation_types" = "bounding box"
if annotation contains "segments_info":
"annotation_types" = "segmentation"

**Comment by jnothman** [comment]
Similarly, we should compute from the annotation a designation of
* Crop present / absent / unknown
* Weed present / absent / unknown

I think these ternary filters would be more useful in UI than the current "Role" filters.
