### ISSUE TITLE
Ease contribution by pulling Collection and AgContext out of the Coco

### ISSUE THREAD

**Issue by jnothman** [Sydney-Informatics-Hub/Weed-ID-Interchange#26]
The idea would be that a new dataset for ingestion consists of:

* one or more COCO files. The things that make them WeedId compatible are that:
  * the categories have sufficient specification to be mapped to one of our central category definitions (e.g. they have `role` and some recognised species identifier).
  * the `info` blob must specify an AgContext name that all the images in that COCO belong to
  * the `info` blob may also specify that it is a specific named subset (e.g. "train" or "test")
* one file conforming to the [schema.org/Dataset](https://schema.org/Dataset) metadata specification. There are a few tools that can help to generate this file.
* one or more AgContext files, each with a distinct name that is used to reference the agcontext within COCO infos.
* image files

So something like:
```
|- dataset.json
|- agcontexts/
| |- illuminated.json
| |- daylight.json
|- cocos/
| |- coco-illuminated-train.json
| |- coco-illuminated-test.json
| |- coco-daylight-train.json
| |- coco-daylight-test.json
|- images/
| |- img01.jpeg
| |- img02.jpeg
| |- ...
```

This allows the contributor to use more pre-existing tools, and avoids convoluted things like `collection_memberships`

**Comment by jnothman** [comment]
This is also closer to being [Arkisto-friendly](https://arkisto-platform.github.io/). If dataset.json were manifest.jsonld, it might be a valid RO-crate?

**Comment by hlydecker** [comment]
This sounds like a sensible compromise in many ways, solving some of our issues without us having to fully drop COCO.

**Comment by jnothman** [comment]
The other way to think of it as this could be another conversion tool input: COCO + meta -> Weed-COCO. In any case, it's low priority.

**Comment by jnothman** [comment]
COCO uploader makes this easy enough?
