### ISSUE TITLE
Upload page has old top level tabs and greyed out About page

### ISSUE THREAD

**Issue by geezacoleman** [Sydney-Informatics-Hub/Weed-ID-Interchange#261]
When on the Upload page (https://weedid.sydney.edu.au/upload), only the old tabs (with the greyed out About tab) are available to the user.

**Comment by jnothman** [comment]
Can you attach a screenshot? I can't currently reproduce this issue. Maybe refresh the page?

**Comment by geezacoleman** [comment]
I tried refreshing a few times/clicking through different links before I submitted the issue and it didn't fix it, but it's now working properly so all good.
