### ISSUE TITLE
Search & faceting widgets

### ISSUE THREAD

**Issue by hlydecker** [Sydney-Informatics-Hub/Weed-ID-Interchange#27]
A core feature we need is the ability to search and facet data. Any changes in the query, either through searching or faceting should affect the page's URL. URLs should be usable for recovering queries.

**Comment by jnothman** [comment]
We should have a free text search over all textual fields, as well as faceting for:
* ML task type
* crop type
* crop growth stage
* weed type
* location (with map-based filtering)
* ?soil type
* ?camera features
