### ISSUE TITLE
Google accounts authorization error

### ISSUE THREAD

**Issue by geezacoleman** [Sydney-Informatics-Hub/Weed-ID-Interchange#274]
Clicking on the 'Sign in with Google' button to upload images brings up a new window with the error: Error 400: redirect_uri_mismatch and the text:

"The JavaScript origin in the request, https://weed-ai.sydney.edu.au, does not match the ones authorized for the OAuth client. Visit https://console.developers.google.com/apis/credentials/oauthclient/${your_client_id}?project=${your_project_number} to update the authorized JavaScript origins."

Could be due to new URL?

**Comment by jnothman** [comment]
Yes it is. Assigning to Elevn.

**Comment by geezacoleman** [comment]
Seems to be working now, thanks @ElevnLi
