### ISSUE TITLE
Signing in doesn't bring up the upload buttons/drop downs

### ISSUE THREAD

**Issue by geezacoleman** [Sydney-Informatics-Hub/Weed-ID-Interchange#279]
Clicked on sign in with Google, which appeared successful but once the popup had disappeared the login/signup options were still there but no option to upload. Also no indication of a successful login.

**Comment by ElevnLi** [comment]
This results from maybe not having the secure certificate, so not able to use cookie for csrf token, which stops most of our actions for now.

**Comment by jnothman** [comment]
Sigh. Waiting on ICT again. Thanks a lot for your testing and issue posting, @geezacoleman!

**Comment by geezacoleman** [comment]
Will you be able to upload the datasets/agcontext/metadata if I link them to you on the RDS? Converters seem to be working without a problem so far.
