### ISSUE TITLE
Metadata editor - name and help buttons/mouseover

### ISSUE THREAD

**Issue by geezacoleman** [Sydney-Informatics-Hub/Weed-ID-Interchange#280]
Metadata editor works well except for a couple of issues I had:

- What's the difference between the required Name field and the Given name and Family Name fields? I entered both but probably just need one.
- ROR ID wasn't obvious at first - googled it, but perhaps add a link/mouse over suggestion on what it is. An optional field for the grant/funding number/code would be helpful to categorise further.

These are lower priority than other issues currently but just logging them as I go through it.

**Comment by geezacoleman** [comment]
Also a convenient feature would be naming the downloaded JSON file the same as the dataset name so they're not lost under one name in my downloads folder.

**Comment by jnothman** [comment]
> What's the difference between the required Name field and the Given name and Family Name fields? I entered both but probably just need one.

Yeah, other names are not required, but could be helpful for some authors who have unconventional names?

Schema.org doesn't currently have a standard way to store grants / funding numbers, so I left it out of there for now... There is a proposed [`MonetaryGrant`](https://schema.org/MonetaryGrant) type, but then there is no standard way to reference it from a Dataset or other CreativeWork.

**Comment by jnothman** [comment]
I will leave funding codes for later work
