### ISSUE TITLE
Image view

### ISSUE THREAD

**Issue by hlydecker** [Sydney-Informatics-Hub/Weed-ID-Interchange#29]
shows an image & masks (still lo-res), licence info, agcontexts it's in, datasets it's in.

**Comment by jnothman** [comment]
we can have med-res, but maybe not ML quality

**Comment by hlydecker** [comment]
Funnily enough even the low res versions may be sufficient for many ML approaches; of course we will still want to retain the full capture resolution images for future use, even if most end users will just downsize to low res versions.

**Comment by jnothman** [comment]
True... I meant that to avoid data licensing issues, we might provide a very lo-res pic.

**Comment by hlydecker** [comment]
Should be relatively easy to render a new page+url for each image, with some info describing the image.
https://github.com/ReactTraining/react-router

**Comment by jnothman** [comment]
Will split this into smaller issues. Too generic
