### ISSUE TITLE
'download JSON' in metadata editor downloads empty JSON file

### ISSUE THREAD

**Issue by geezacoleman** [Sydney-Informatics-Hub/Weed-ID-Interchange#299]
I can still copy the JSON information to a new file, but the download JSON button just downloads an empty file.

**Comment by jnothman** [comment]
I am not managing to replicate this. You will need to run one of us through how to reproduce this.

**Comment by geezacoleman** [comment]
I don't know what was happening here - it was Schrodinger's JSON for a while (had contents until you opened it). Anyway, it's working now ok so all good. Possibly something to do with the editor I was using.
