### ISSUE TITLE
Export functionality

### ISSUE THREAD

**Issue by hlydecker** [Sydney-Informatics-Hub/Weed-ID-Interchange#31]
Relatively self explanatory; users need to be able to export

**Comment by jnothman** [comment]
We've actually not put this in the current scope

**Comment by jnothman** [comment]
As in, export is for a later phase of development

**Comment by hlydecker** [comment]
Got it, I'll close this issue for now then.

**Comment by jnothman** [comment]
Can keep it open but group work into milestone tags or another prioritisation system
