### ISSUE TITLE
Clicking on any dataset link opens blank white page

### ISSUE THREAD

**Issue by geezacoleman** [Sydney-Informatics-Hub/Weed-ID-Interchange#320]
Dataset uploaded fine, went to review stage but clicking on the dataset name briefly (<0.5s) flicked up some page before going to a blank white page. Can accept/reject but can't see any data.

**Comment by jnothman** [comment]
Yes, it seems I created an unseen bug in #266 :(
Fixing.

**Comment by geezacoleman** [comment]
Looks like it's for any dataset link, even from main screen. Thanks!
