### ISSUE TITLE
[Errno 13] Permission denied to images on upload

### ISSUE THREAD

**Issue by geezacoleman** [Sydney-Informatics-Hub/Weed-ID-Interchange#327]
Upload fails when processing.

**Comment by jnothman** [comment]
this was due to a failed attempt to fix #252, which has now been reverted.

**Comment by geezacoleman** [comment]
Still getting this error on certain datasets with the camera with larger images : [Errno 13] Permission denied: '/code/upload/2/331a89be-812d-493c-99df-eec884663c15/images/19345082_cpst2june30__201414.jpg'

**Comment by jnothman** [comment]
Have you received that repeatedly, or only once? I've not yet got a good clue as to its cause. The file exists and I had thought would be accessible to a Celery worker.

@ElevnLi, I can see some files in `upload/` with `-rw-r--r--.` and others with `-rw-------.` but I don't know why that would eventuate.

**Comment by geezacoleman** [comment]
I get it repeatedly: [Errno 13] Permission denied: '/code/upload/3/912d9e04-038c-4489-ae0c-ee34b0f0cfb4/images/19345061_ld_wht_tos4_mix_night_20201014_115608.jpg' 

This was for an unseen dataset from a separate Google account.

**Comment by jnothman** [comment]
This seems to be related to a previous issue we had when moving files from a temporary directory in a container to a docker-managed volume. We couldn't understand why we couldn't delete or view files.
