### ISSUE TITLE
Inconsistent Elasticsearch indexing

### ISSUE THREAD

**Issue by ElevnLi** [Sydney-Informatics-Hub/Weed-ID-Interchange#328]
There are lots of datasets that are able to be deposited and indexed without an error but the index actually doesn't go into Elasticsearch. I've tested directly to Elasticsearch container and with the module independently. Sometimes it's giving a deprecated warning for having _type, but when I remove _type from the index, the warning disappeared. However, the index was still not injected. There's no indication why this is the case, even an inexplicit one. @jnothman please have a look. Guy and I have exhausted everything last night but couldn't figure out why.

**Comment by geezacoleman** [comment]
@ElevnLi I tried another dataset similar to the Wheat dataset we tried last night and it works fine this morning. There must be something specific to those other datasets that means they won't index in elasticsearch.

**Comment by jnothman** [comment]
This was not a problem with indexing, but with display
