### ISSUE TITLE
Support search with different variant growth stage descriptors

### ISSUE THREAD

**Issue by jnothman** [Sydney-Informatics-Hub/Weed-ID-Interchange#35]
Per the matrix sent by Guy & Michael, there are many ways to refer to the same stage of crop growth.

We have two choices about how to handle this:
1. Store the most specific label for an agcontext in the ES index, then provide a frontend widget that allows aliases and converts them into the indexed form for querying.
2. Expand the label given in the agcontext when the data is indexed, and index the list of alternative growth stage labels in each image. Then these become labels that will be auto-suggested for category search.

**Comment by jnothman** [comment]
We're talking about taking approach number 2.

**Comment by hlydecker** [comment]
We will update how we handle growth stages to treat them as ranges rather than simple regular explressions

**Comment by jnothman** [comment]
Duplicate of #192
