### ISSUE TITLE
Define one or more places in the schema to store DCMI terms

### ISSUE THREAD

**Issue by jnothman** [Sydney-Informatics-Hub/Weed-ID-Interchange#6]
[DCMI](https://www.dublincore.org/specifications/dublin-core/dcmi-terms) is the standard for describing creative works and their provenance, e.g. datasets. It would be appropriate to ascribe images and/or annotations to originating datasets using this standard.

**Comment by hlydecker** [comment]
DCMI likes UpperCamelCase; whereas we are following in COCO's footsteps and using snake_case. For the collections object blob should we make an exception and use UpperCamel to fit with DCMI?

**Comment by jnothman** [comment]
Interesting question. I suppose we should (?).

**Comment by hlydecker** [comment]
I'm going to see what it looks like if we populate the "collections" object with information fitting the DCMI standards... I've been reading through metadata and elements documents to try and better understand the proper DCMI standards to use.

**Comment by jnothman** [comment]
We have `collection` objects already in master
