### ISSUE TITLE
Schema could constrain the valid range of latitude and longitude

### ISSUE THREAD

**Issue by jnothman** [Sydney-Informatics-Hub/Weed-ID-Interchange#60]
It could also constrain the allowed location_datum, and for now it could be required to be 4236

**Comment by hlydecker** [comment]
Only allowing 4326 is reasonable for now; that also makes it easy to impose constraints on the possible lat/long values.

**Comment by hlydecker** [comment]
It looks like we may want to store location as a "geopoint" ala https://rnfirebase.io/reference/firestore/geopoint.

We could also convert lat/long into a geopoint as part of the elastic search ingestion process.

**Comment by hlydecker** [comment]
Here are all the options for geo_points from ES: https://www.elastic.co/guide/en/elasticsearch/reference/current/geo-point.html

**Comment by jnothman** [comment]
I assume you mean storing a GeoPoint when indexing with ES, not storing it as such in Weed COCO?
