### ISSUE TITLE
Will need an explicit schema on ElasticSearch; or change "variable" and "na" into NULL

### ISSUE THREAD

**Issue by jnothman** [Sydney-Informatics-Hub/Weed-ID-Interchange#61]
ES seems to have done some type sniffing, which is a problem for something like `camera_fov`, since it is detected as a numeric type, and then a later dataset might say "variable" and it breaks. The other option might be to store "variable" as null in the index, thus avoiding the problem (currently implemented in #49).

https://github.com/kristianmandrup/json-schema-to-es-mapping might help. I've only found it, not looked at it.

**Comment by hlydecker** [comment]
bugger I was worried that we would need to do something like that. So far I've only really interacted with things like `crop_type` that are strings and can be easily used as keywords by ES.
