### ISSUE TITLE
Frontend: second draft

### ISSUE THREAD

**Issue by hlydecker** [Sydney-Informatics-Hub/Weed-ID-Interchange#62]
- Improve UI
- Change faceting/filtering behaviour to be and rather than or
- Change URL based on search params
- Add mapping widget

Anything else @jnothman ?

**Comment by hlydecker** [comment]
Somewhere along the line I need to get the main searchbox to work properly; currently it seems to be useless. The text boxes for each of the filters seem to work very well, so it is strange how this one doesn't seem to work.

On the topic of searchboxes, it also seems that we have to generate a list of items to show up as suggestions when users type into the search bar.

**Comment by jnothman** [comment]
>  it also seems that we have to generate a list of items to show up as suggestions when users type into the search bar.

I'd assume that ES provides some way to get a list of (common) indexed terms for each field, as it's very similar to the aggregates shown in faceted search.

> Somewhere along the line I need to get the main searchbox to work properly; currently it seems to be useless. 

What do you intend its purpose to be? Which fields will it search? If unneeded, should we remove it?

**Comment by hlydecker** [comment]
I was originally thinking a general search box across all data fields (or at least the big ones) might be useful
