### ISSUE TITLE
react-scripts not found

### ISSUE THREAD

**Issue by hlydecker** [Sydney-Informatics-Hub/Weed-ID-Interchange#63]
Issues with react-scripts have resurfaced. Reactivesearch doesn't work with master currently; this is because react-scripts are not found when running `docker-compose up`.

Currently trialing various attempts to fix this in the dockerfile and/or docker-compose.

```
Attaching to search_kibana_1, elasticsearch, search_reactivesearch_1, dejavu
reactivesearch_1  | 
reactivesearch_1  | > weed-search@0.1.0 start /code
reactivesearch_1  | > react-scripts start
reactivesearch_1  | 
reactivesearch_1  | sh: 1: react-scripts: not found
reactivesearch_1  | npm ERR! code ELIFECYCLE
reactivesearch_1  | npm ERR! syscall spawn
reactivesearch_1  | npm ERR! file sh
reactivesearch_1  | npm ERR! errno ENOENT
reactivesearch_1  | npm ERR! weed-search@0.1.0 start: `react-scripts start`
reactivesearch_1  | npm ERR! spawn ENOENT
reactivesearch_1  | npm ERR! 
reactivesearch_1  | npm ERR! Failed at the weed-search@0.1.0 start script.
reactivesearch_1  | npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
reactivesearch_1  | 
reactivesearch_1  | npm ERR! A complete log of this run can be found in:
reactivesearch_1  | npm ERR!     /root/.npm/_logs/2020-09-04T03_59_05_412Z-debug.log
search_reactivesearch_1 exited with code 1
```

**Comment by jnothman** [comment]
The issue wasn't with `react-scripts`. It's that the node_modules used for install is not available at runtime.

Is this an issue you're finding on your local machine, or on CI?

**Comment by jnothman** [comment]
I can't currently reproduce this issue on my machine

**Comment by hlydecker** [comment]
Local machine;

```
Last login: Fri Sep  4 14:26:32 on ttys008
➜  search git:(frontend2) ✗ ls
Dockerfile             docker-compose.yml     package.json           src
README.md              live-data              public                 test_search_input.json
build                  node_modules           scripts                yarn.lock
➜  search git:(frontend2) ✗ npm ls react-scripts
weed-search@0.1.0 /Users/hlyd4326/Documents/sih_projects/Weed-ID-Interchange/search
└── react-scripts@3.4.3 
```

**Comment by jnothman** [comment]
Docker doesn't care about the npm ls on the host machine. Check you're using the latest version of docker-compose.yml though.

**Comment by jnothman** [comment]
(assuming you're launching with docker-compose not the host environment)

**Comment by hlydecker** [comment]
I managed to find a solution by running `docker-compose build` to recreate the needed node modules. Now reactivesearch correctly loads when using `docker-compose up`

**Comment by jnothman** [comment]
Ahh, right: you were using the new docker-compose.yml, but had an image built on an old Dockerfile. You can make a point of using `docker-compose up --build`
