### ISSUE TITLE
Should we use queryFormat: "or" for multiselect categories?

### ISSUE THREAD

**Issue by jnothman** [Sydney-Informatics-Hub/Weed-ID-Interchange#79]
If an image has multiple values for some field, we might want "and" otherwise it's useless. Users will certainly want to be able to express "or" across values for a field. So if we don't use `queryFormat: "or"`, we will need to provide some kind of advanced search interface to combine queries by disjunction. OTOH, `queryFormat: "and"` behaves more intuitively.

**Comment by hlydecker** [comment]
Would a UI element for toggling between "and" / "or" be useful/feasible?  So far from limited googling I can't find any clear solutions for that. 

 Or should we just decide that there are some fields where we only want "and" and others where we would only want "or".

**Comment by jnothman** [comment]
Most of the fields we're dealing with are single-valued, so "or" makes sense. I just couldn't make sense of the numbers when I did that. As in we want users to be able to express "I want all images with segmentation annotation, of species x or y"

**Comment by hlydecker** [comment]
I'm having a hard time imagining where "and" would be useful. 

Interestingly, when just swapping to `quertFormat: "or" `, it doesn't behave like I expected.  You aren't able to select multiple options.

**Comment by hlydecker** [comment]
Ok, we also need to change the "and" in ` react: { and: [things to react to] } ` to "or". This now behaves how we would like.
