### ISSUE TITLE
Engineering for extendable datasets

### ISSUE THREAD

**Issue by hlydecker** [Sydney-Informatics-Hub/Weed-ID-Interchange#9]
I've made some changes to try and support a hypothetical future where users can filter, search, and combine multiple datasets. This basically means that for data set level info, I have added in identifiers for them in images, and made it so the "agadata" object is actually a set of "agdataset" objects. Naming should probably be reviewed to make sure it makes sense, because I know this can get confusing.

**Comment by jnothman** [comment]
I wonder if this can be closed?

**Comment by hlydecker** [comment]
Yes, this is a very retro issue; we are past this now :)
