### ISSUE TITLE
Deploy frontend to weedid.sydney.edu.au:80

### ISSUE THREAD

**Issue by jnothman** [Sydney-Informatics-Hub/Weed-ID-Interchange#93]

**Comment by ElevnLi** [comment]
I pushed to this commit d737e5f, where 3 servers are sitting behind the reverse proxy, and
localhost --> reactsearch
localhost/dashboard --> kibana
localhost/elasticsearch --> elasticsearch
I was trying hard to fix the kibana issue as it wasn't able to retrieve contents and render the page from different uri. It finally worked with a new server.basePath. And the reason I was stuck last Friday was that I didn't include nginx to the same docker network.
This is working locally now but as I observed the latest version docker on our vm is 1.13, which doesn't support multi stage build for react. I was looking for repo to install docker after 1.17.06 with Sergio but we didn't make it. I'm looking for alternative approach for this part.

**Comment by jnothman** [comment]
Fwiw, I don't think we want kibana accessible to the public. Kibana access can be available to admins through SSH tunnels...
I've never met multi-stage builds. They look like a neat way to combine multiple resources into a final build.

**Comment by jnothman** [comment]
Could you create a PR for the branch where you are implementing this? https://github.com/Sydney-Informatics-Hub/Weed-ID-Interchange/compare/nginx

**Comment by ElevnLi** [comment]
Kibana can be protected by nginx basic authentication, and the valid credentials can be stored in /opt/nginx/config/htpasswd. It could be an option though.

**Comment by jnothman** [comment]
Yes, we could have Kibana open only to users with particular access levels.

https://docs.docker.com/engine/install/binaries/ might be a solution for docker, if need be.

**Comment by jnothman** [comment]
How is this still open?
