### ISSUE TITLE
Distinguishing between species in segmentation masks

### ISSUE THREAD

**Issue by hlydecker** [Sydney-Informatics-Hub/Weed-ID-Interchange#95]
This issue was brought up by Guy: 

>The weed species information is on an image-wise basis, but I was wondering how you were doing that for segmentation masks where the colour/shade of the mask refers to individual species but where that information is only encoded at the start. Would we need to define which colours referred to which weed (in some input box if you select segmentation?) and then have a bit of code go over every image and check for that colour and then assign a weed id, or is this already covered in the COCO standard?

**Comment by jnothman** [comment]
COCO doesn't store masks as a PNG, but rather as polygons or a bitmap mask for each annotation, and it stores the category with each annotation.

So I see this mapping from colour to category name as part of conversion (#34), just as the VOC converter accepts a mapping from the stored category name to the WeedCOCO category name (see https://github.com/Sydney-Informatics-Hub/Weed-ID-Interchange/pull/49/files#diff-e37c5d148e72b97d1fd2e23d9c762251R1-R2 for an example, and https://github.com/Sydney-Informatics-Hub/Weed-ID-Interchange/pull/49/files#diff-4d5ea174a60cf1f936d2a94f354e36aeR117-R121 for the logic of loading it).

**Comment by jnothman** [comment]
Fixed in segmentation mask importer
